### ISSUE TITLE
Losing anchors when switching language

### ISSUE THREAD

**Issue by migmake** [lindseydiloreto/craft-languagelink#11]
Is it possible to keep the anchors from the url when switching language ?

I have this code for my switcher 

```
        <div id="language-switcher">
                {% for locale in craft.i18n.getSiteLocales %}
                {% set active = (locale.id == craft.locale) %}
                <a href="{{ ll(locale.id) }}" class="menu-link button lang {{ active ? 'active' }}">{{ locale.nativeName|capitalize|slice(0,2) }}</a>
                {% if locale.id == "en" %}<span class="sep">/</span>{% endif %}
                {% endfor %}
            </div>
```

**Comment by lindseydiloreto** [comment]
Great question!

Unfortunately, [it's not possible to get the anchor fragment in PHP](http://stackoverflow.com/questions/967649/get-entire-url-including-query-string-and-anchor). Therefore, the plugin cannot append the fragment back to the end of the URL.

That being said, you may be able to detect & append the fragment via Javascript, once the page has finished loading.
