### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by Delonvdv** [lindseydiloreto/craft-languagelink#12]
Less of an issue, more of a question.

Will this plugin be updated to be Craft 3 compatible?

**Comment by lindseydiloreto** [comment]
Absolutely!

I've converted about half of our plugins so far, and working on the remaining half. This one is definitely going to be ported, hopefully by the end of January or February.

**Comment by Delonvdv** [comment]
Awesome, thanks for the quick response

**Comment by lindseydiloreto** [comment]
No problem! 👍

**Comment by groe** [comment]
Any news yet? Craft 3 has been released today :)

**Comment by lindseydiloreto** [comment]
Indeed, happy Craft 3 day! 🎉 

It's still on the list, but got bumped back a little bit. I had to shift priorities to port some of my commercial plugins a little more quickly.

I'm hoping to have this one ported within the next 1-2 months. By the end of May at the latest (theoretically).

**Comment by outline4** [comment]
Hi, any news on this?  
I slowly start to migrate all of my v2 sites...  
Your plugin is very handy and it would be great to have it on v3...

**Comment by lindseydiloreto** [comment]
I'm finally starting to wrap up with some of the more complex plugins in our catalogue... [Ad Wizard](https://github.com/doublesecretagency/craft-adwizard) took waaaay longer than expected.

It's looking like I'll be able to tackle Language Link within the next 2-4 weeks. Assuming things go according to plan, I'm hoping to have it released by the end of August.

**Comment by outline4** [comment]
That's great news!

**Comment by lindseydiloreto** [comment]
Good news... this plugin has been officially released for Craft 3! Now available in the plugin store!  🎉 

<img width="299" alt="in the Plugin Store" src="https://user-images.githubusercontent.com/5309692/44872072-7593a300-ac49-11e8-8de6-d3cac59f6b4e.png">

I've renamed it to "Site Switcher", because the underlying concept of _locales_ has evolved into _sites_.
