### ISSUE TITLE
How to check if translated page exists? 

### ISSUE THREAD

**Issue by amityweb** [lindseydiloreto/craft-languagelink#13]
How to check if translated page exists? So instead of linking to the default page, we can check if it exists and not output a link at all if it doesnt. 
Thanks

**Comment by lindseydiloreto** [comment]
Sorry for the delayed response... I've just added instructions for this to the README.

https://github.com/doublesecretagency/craft-siteswitcher#checking-whether-a-translated-element-exists

It's pretty straightforward. Just get the link, and if it doesn't exist you can skip it.

```twig
{% set element = (category ?? entry ?? null) %}

<ul>
    {% for site in craft.app.sites.getAllSites() %}
        {% set siteLink = siteSwitcher(site.handle, element) %}
        {% if siteLink %}
            <li><a href="{{ siteLink }}">{{ site.name }}</a></li>
        {% endif %}
    {% endfor %}
</ul>
```
