### ISSUE TITLE
Non Element Url Problem

### ISSUE THREAD

**Issue by wizzer711** [lindseydiloreto/craft-languagelink#14]
Hi,

I am using craft 3's multisite manager to control 3 sites and have used your documented snippet:

```
{% for site in craft.app.sites.getAllSites() %}
    <a href="{{ siteSwitcher(site.handle, element) }}">{{ site.name }}</a>
{% endfor %}
```
the site urls I have setup are basically the site with the addition of each language eg:

http://site.com (primary site)
http://site.com/de
http://site.com/cn

When i go from http://site.com and use the link generated by SiteSwitcher it successfully goes navigates to say http://site.com/de but once here if i try and use one of the links again it appends the end of the current url to generated one.

eg: If i try to go from http://site.com/de to http://site.com/cn the url generated in the link looks like: http://site.com/cn/de

Any idea on why it does this would be great.

Thx in advance.

**Comment by lindseydiloreto** [comment]
Hi @wizzer711,

The short answer is, it has something to do with how you're setting your `siteUrl` or `baseUrl`. I can't remember the specifics off the top of my head, so hopefully this is enough to point you in the right direction.

Here's the Site URL part of the docs for multisite (which I'm sure you've already seen)...

https://docs.craftcms.com/v3/sites.html#site-url

Also note the warning about using `@web` to define your URLs.

Let me know if you're still stuck after tweaking those URLs.

**Comment by lindseydiloreto** [comment]
It turns out this was actually due to a bug in the plugin. I've pushed a fix for it, so just update to the latest version (2.1) and it should work correctly. 👍
