### ISSUE TITLE
Doesn't work with channel page

### ISSUE THREAD

**Issue by Ekkiwnox** [lindseydiloreto/craft-languagelink#15]
Hello,
Seems that this plugin doesn't work with Channel pages.

I've a template with two file:
blog/index.html
blog/_entry.html

Both doesn't want to be translate :-(

**Comment by Ekkiwnox** [comment]
After a few try, I think I've found where the issue is exactly ! 
This is the structure of my templates :
blog/index.html
blog/_entry.html
As I said, it's a channel type of page.

When I use the langage switcher, it works perfectly on the _entry and on the single and structure pages. But one I tried to change the language on blog/index.html, it seems that the url is duplicated.

Example :
For a single page **NameOfThePage/en**
For the channel page **NameOfThePage/en/NameOfThePage/en** > so it doesn't work :-/

**Comment by lindseydiloreto** [comment]
Hi there! Those should definitely both work. Can you post your code snippet?

**Comment by Ekkiwnox** [comment]
```
{% set element = (category ?? entry ?? null) %}
		<ul>
			{{ siteSwitcher(site.handle, element) }}
		    {% for site in craft.app.sites.getAllSites() %}

		        <li><a href='{{ siteSwitcher(site.handle, element) }}'>{{ site.name }}</a></li>
		    	
		    {% endfor %}
		</ul>
```

**Comment by lindseydiloreto** [comment]
After doing a bit of digging, it turns out there was a bug in the plugin for static pages!

Grab the latest version (2.1), and let me know if that solves the problem for you.
