### ISSUE TITLE
Slug not translated for Craft Commerce

### ISSUE THREAD

**Issue by amityweb** [lindseydiloreto/craft-languagelink#16]
Does this work with Craft Commerce? Its working fine for other Craft sections, but for our Craft Commerce products, it does not fetch the translated slug. It is fetching only the slug of the language you are on. 

We are using the following URL Format for products, because we want the URLs to include their related categories which are in a different section. 
`{relatedPage.first().uri}/{slug}`

Here is our code:
```
{% for site in craft.app.sites.getAllSites() %}
    
    {% if site.id != currentSite.id %}

    	{% set siteSettings = craft.app.getGlobals().getSetByHandle('siteSettings', site.id) %}
    	{% if siteSettings.siteEnabled %}
    		{% set link = siteSwitcher(site.handle, element) %}
    		{% set countryFlag = siteSettings.countryFlag.first() %}
            {% if link is defined %}
                <a class="language" href="{{ link }}">
                    {% if countryFlag %}
                        <img class="country-flag" src="{{ countryFlag.url }}" alt="{{site.handle}}" title="{{ siteSettings.countryName }}">
                    {% else %}
                        {{site.handle}}
                    {% endif %}
                </a>
            {% endif %}
            
               
        {% endif %}
    
    {% endif %}
     
{% endfor %}
```

**Comment by lindseydiloreto** [comment]
Hi @amityweb, how are you setting the value of `element`?

In theory, it _should_ work just fine for Commerce products. Is this for Craft 2 or 3?

**Comment by amityweb** [comment]
Craft 3.
I got it working now following your question about setting element. 

Does element default to entry perhaps? Because setting element was missing. Its missing on another site we have (we dont use commerce on it). But SiteSwitcher still works, so we never realised we were missing defining element, and I guess it defaults to entry hence working. 

So I now added this and its working OK:
`{% set element = (entry ?? product ?? null) %}`

Thanks!

**Comment by lindseydiloreto** [comment]
It actually doesn't default to any element type. Setting it the way you did now is perfect. 👍 

If no element is specified (default), then it will try to cleverly guess the parallel URLs. Sounds like you got lucky, and the parallel URLs were straightforward enough to match.

Glad you got it sorted out!
