### ISSUE TITLE
Display selected language + Active link

### ISSUE THREAD

**Issue by thefubon** [lindseydiloreto/craft-languagelink#19]
Tell me how to implement this solution as in my screenshot?

![Language---SiteSwitcher](https://user-images.githubusercontent.com/43171309/87430152-7b03f780-c5ed-11ea-8e01-0c7904d07a5a.jpg)

**Comment by lindseydiloreto** [comment]
Replace the first piece with this...
```twig
<a href="#">{{ currentSite.name }}</a>
```

And the second piece with this...
```twig
{% set isCurrentSite = (site.id == currentSite.id) %}
<li><a href="{{ siteSwitcher(site.handle, element) }}" class="{{ isCurrentSite ? 'active' }}">{{ site.name }}</a></li>
```

**Comment by thefubon** [comment]
Very cool! Thank!

**Comment by thefubon** [comment]
Is it possible to hide the active language in the list of languages?
