### ISSUE TITLE
as well as how to display a translation of the text in the language of the region from which you came

### ISSUE THREAD

**Issue by thefubon** [lindseydiloreto/craft-languagelink#20]
Who knows how to enable cookies or cache for the close (hide) button if you restart the browser, a button is still displayed about a language change suggestion

```{% set redirectInfo = craft.geomate.redirectInformation() %}
  {% if redirectInfo %}
  <div class="uk-background-muted uk-padding-xsmall" data-uk-alert>
  <a class="uk-alert-close" uk-close></a>
    <div class="uk-container uk-container-medium">
      <div class="uk-grid-small uk-flex-middle" data-uk-grid>
        <div class="uk-width-expand uk-text-meta">Select a country or region so that the content matches your location.</div>
        <div class="uk-width-auto"><a class="uk-button uk-button-primary uk-border-rounded uk-text-transform-none" href="{{ redirectInfo.url }}">{{ redirectInfo.site.name }}</a></div>
      </div>
    </div>
  </div>
  {% endif %}```

as well as how to display a translation of the text in the language of the region from which you came

https://user-images.githubusercontent.com/43171309/87527462-d50bc800-c694-11ea-9a4f-3ffd7bc0d7c2.gif

**Comment by thefubon** [comment]
In the settings, I specify the auto redirect, but I can not choose another language. Somehow it is possible to automatically include site.com/en But if I change to another, then the path and language change

**Comment by lindseydiloreto** [comment]
Hi @thefubon,

I don't really understand your question. Site Switcher is a simple Twig mechanism for rendering HTML in whichever way you choose. Anything beyond what Twig renders is outside the scope of Site Switcher.

I encourage you to ask on Discord, since this doesn't seem to be a Site Switcher problem. Feel free to correct me if you believe I am mistaken.
