### ISSUE TITLE
Language selection via select

### ISSUE THREAD

**Issue by thefubon** [lindseydiloreto/craft-languagelink#21]
Please tell me how to change the language through the &lt;select>

&lt;select name="language-picker-select" id="language-picker-select">
&nbsp;&nbsp;&lt;option lang="de" value="deutsch">Deutsch&lt;/option>
&nbsp;&nbsp;&lt;option lang="en" value="english" selected>English&lt;/option>
&nbsp;&nbsp;&lt;option lang="fr" value="francais">Français&lt;/option>
&nbsp;&nbsp;&lt;option lang="it" value="italiano">Italiano&lt;/option>
&lt;/select>

**Comment by lindseydiloreto** [comment]
You would probably want to set the alternate URL as the `value` of each option...

```twig
<option lang="en" value="{{ siteSwitcher('english', element) }}">English</option>
```

Then use JavaScript to redirect the page when the dropdown is changed.
