### ISSUE TITLE
Question:: It is possible to get site attributes

### ISSUE THREAD

**Issue by zzseba78** [lindseydiloreto/craft-languagelink#22]
It is possible to get site attributes like title, id, slug, and so on with this plugin? thank you

**Comment by lindseydiloreto** [comment]
Unless I'm misunderstanding the question... you don't _need_ this plugin to get the site attributes for you. In theory, you will already have access to the attributes you need.

From the docs...

```twig
{% set element = (category ?? entry ?? null) %}

<ul>
    {% for site in craft.app.sites.getAllSites() %}
        <li><a href="{{ siteSwitcher(site.handle, element) }}">{{ site.name }}</a></li>
    {% endfor %}
</ul>
```

Within the context of that loop, you could access `site.id` or any other attributes associated with each site.

Hope that helps!
