### ISSUE TITLE
Additional parameters in URL disappear on language change

### ISSUE THREAD

**Issue by Szabx** [lindseydiloreto/craft-languagelink#3]
Hi,

I'm trying to figure out what needs to be changed for additional url parameters to be passed on language change. For example I have a url like en/search?cat1=val1&cat2=val2 on language change becomes de/search.

Regards,
Szabolcs

**Comment by lindseydiloreto** [comment]
Interesting, thanks for the feedback. I'll have to do some testing around that URL format.

Right now, the plugin may not support query string parameters (I haven't actually tested that). But if it's possible to convert those query string parameters into url segments, that should hold up during translation.

```
en/search/val1/val2
```

I'll investigate this further... In theory, the plugin should be capable of supporting query string parameters.

**Comment by lindseydiloreto** [comment]
This is fixed! As of **v1.1.0**, all query string parameters will be maintained when switching between languages.

Probably too late to matter for your project, but thought you might want to know anyway. :)

**Comment by Szabx** [comment]
Thank You for your work!
It will definitely be useful in future projects.

Regards,
Szabolcs
