### ISSUE TITLE
Homepage link not good

### ISSUE THREAD

**Issue by migmake** [lindseydiloreto/craft-languagelink#6]
Hi Lindsey.
Thank you for this great plugin.

It works great for entries links but not for the homepage. It was still english link when I clicked on Francais link.

I had to do this.

```
{% set element = (entry is defined ? entry : null) %}
<ul>
    <li><a href="{{ ll('en', element) }}">English</a></li>
    <li><a href="{% if bodyClass == "homepage" %}{{ ll('fr') }}{% else %}{{ ll('fr', element) }}{% endif %}">Français</a></li>
</ul>
```

Any idea ?

**Comment by lindseydiloreto** [comment]
It _should_ work for the homepage... ping me on Slack and we can walk through it together.

**Comment by lindseydiloreto** [comment]
Did you get this working? If this is no longer an issue, we can close the thread.

**Comment by migmake** [comment]
No never resolved it.
I am available on slack so I can try and test again and we could try to go through.

I test again and ping you tomorrow
Thx

Miguel

**Comment by lindseydiloreto** [comment]
I still haven't heard from you on this issue.

It's been 4 months, so I'm going to assume you've resolved the issue by now.
