### ISSUE TITLE
Language switcher not working with subfolders

### ISSUE THREAD

**Issue by 88kbbq** [lindseydiloreto/craft-languagelink#7]
On http://testing.88k.com.tw, I have the default language set to Chinese and the English language in as a subfolder. I set up siteurls as such

```
'siteUrl' => array(
         'zh' => 'http://testing.88k.com.tw/',
         'en' => 'http://testing.88k.com.tw/en/',
        )
```

Perhaps your plugin doesn't handle this or am I missing something?

**Comment by lindseydiloreto** [comment]
That looks like it should work... What URLs are your links actually generating?

Can you paste the Twig snippet you're using with the Language Link code?

**Comment by lindseydiloreto** [comment]
Did you work this out? If this is no longer an issue, I will close this thread.
