### ISSUE TITLE
Active language detection to make active style link different

### ISSUE THREAD

**Issue by migmake** [lindseydiloreto/craft-languagelink#8]
Hi.
How is detected the active language so we can use a class active on the language active button to use different style and make a difference between the active and inactive link.

**Comment by lindseydiloreto** [comment]
Yes, this is very easy. Use `craft.locale` to get the current locale...

```
{% set active = (locale.id == craft.locale) %}
```

In a full loop of locales, it would look something like this...

```
{% for locale in craft.i18n.getSiteLocales %}
    {% set active = (locale.id == craft.locale) %}
    <a href="{{ ll(locale.id) }}" class="{{ active ? 'active' }}">{{ locale.nativeName|capitalize }}</a>
{% endfor %}
```

**Comment by migmake** [comment]
Perfect thanks Lindsey ! 
Sorry for delay to reply (holiday big break... :)
