### ISSUE TITLE
Locale short name?

### ISSUE THREAD

**Issue by migmake** [lindseydiloreto/craft-languagelink#9]
Is it possible to display locale shortname (FR / EN) instead of full name (FRANCAIS / ENGLISH) in your example?

```
{% set element = (category ?? entry ?? null) %}
<ul>
    {% for locale in craft.i18n.getSiteLocales %}
        <li><a href="{{ ll(locale.id, element) }}">{{ locale.nativeName|capitalize }}</a></li>
    {% endfor %}
</ul>
```

**Comment by lindseydiloreto** [comment]
When you loop through all locales, as in that example...

```
{% for locale in craft.i18n.getSiteLocales %}
```

... you will be dealing with a [LocaleModel](https://craftcms.com/classreference/models/LocaleModel).

_**I highly recommend you read up on the LocaleModel to learn what properties and methods are available to it.**_

The one you are looking for is this...

```
locale.id
```
